### ISSUE TITLE
Stacks 2.1: Support sending coinbase rewards to smart contracts

### ISSUE THREAD

**Issue by pxydn** [stacksgov/sips#20]
In the current implementation, coinbase rewards are only able to be sent to STX addresses. 

For example, mining pools controlled by smart contracts (like [metaverse pool](https://github.com/mtavrse/pool)) currently have to have the rewards sent to the contract from the pool, putting unnecessary trust in the mining pool and increasing transaction fees. 

If the rewards could be sent directly to the contract in charge of managing payouts, this would be beneficial.

**Comment by jcnelson** [comment]
Miners can always include a transaction in the blocks they mine that immediately sends their matured block rewards to a particular contract.  In the context of pools, because the pool participants all see the block template (i.e. they have the block hash) before they commit BTC, they can independently confirm that the STX are going to the right disbursal contract.

**Comment by DyrMooning** [comment]
Can we get a term for this and anyone know which miners are using this feature?

**Comment by pxydn** [comment]
> Can we get a term for this and anyone know which miners are using this feature?

none are right now. [L3 pool will though](https://github.com/labs3/pool)
