### ISSUE TITLE
Governance Consideration Advisory Board

### ISSUE THREAD

**Issue by whoabuddy** [stacksgov/sips#26]
Officially expressing my interest here!

**Comment by joberding** [comment]
Piling on and adding my interest as well. :)

**Comment by jcnelson** [comment]
Thank you both for volunteering!  I just need your emails, and I'll add you to this doc: https://github.com/stacksgov/sips/blob/main/considerations/governance.md

This doc is meant to describe the governance advisory board's bylaws. If @HaroldDavis3 wants to join as well, then the board will officially exist apart from the steering committee!  After this, I'll need y'all to do the following:

* Adopt a set of bylaws that describe, at a minimum, what's in-scope and what's out-of-scope for this CAB.  This way, when someone goes and submits a SIP, the SIP editors and steering committee can look at this document and figure out whether or not it needs the attention of the governance CAB in order to advance the SIP to "Recommended" status.

* Pick a chairperson who will serve as the "cat-herder" for the group.  This person's duties is to be the point of contact for the CAB, and to make sure the bylaws are adhered to.

Since this CAB technically exists already (albeit in a stub form), you don't need to write a SIP to officially create it -- it was instantiated as part of SIP-000's ratification.  Just updating the above doc with a description of what this CAB's purview will be should be sufficient.

**Comment by HaroldDavis3** [comment]
> Officially expressing my interest here!

Officially doing the same ✅

**Comment by jcnelson** [comment]
Thanks @HaroldDavis3!  Just need your email address

**Comment by HaroldDavis3** [comment]
> Thanks @HaroldDavis3! Just need your email address

tried to DM on discord please add or i can send elsewhere ofcourse :)

**Comment by jcnelson** [comment]
cool, just accepted your friend request @HaroldDavis3!

So, who wants to be the chairperson?  It can't be me, since I'm on the steering committee, and we now have three members of this CAB.

**Comment by whoabuddy** [comment]
I can take that on unless anyone objects 🙂 

Also, will start a Discord group so the three of us can start discussing bylaws.
