### ISSUE TITLE
Reference List of Traits for Mainnet and Testnet

### ISSUE THREAD

**Issue by radicleart** [stacksgov/sips#94]
There is currently no single reference for traits defined by the Stacks Improvement Process.

A document maintained in this repo which lists recommended trait contracts already deployed will be helpful to new and existing developers.

SIPs 009 and 010 reference a deployed mainnet trait contract but not testnet versions. Versions for testnet are included below along with the new SIP-013 standard which is deployed on testnet but not yet ratified.

## Mainnet

**[SIP-009](https://github.com/stacksgov/sips/blob/main/sips/sip-009/sip-009-nft-standard.md)**
[SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait.nft-trait](https://explorer.stacks.co/txid/0x80eb693e5e2a9928094792080b7f6d69d66ea9cc881bc465e8d9c5c621bd4d07?chain=mainnet)

**[SIP-010](https://github.com/stacksgov/sips/blob/main/sips/sip-010/sip-010-fungible-token-standard.md)**
[SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard.sip-010-trait](https://explorer.stacks.co/txid/0x99e01721e57adc2c24f7d371b9d302d581dba1d27250c7e25ea5f241af14c387?chain=mainnet)

**[SIP-013](https://github.com/stacksgov/sips/pull/42)** not yet ratified / deployed

## Testnet

**SIP-009**
[ST1NXBK3K5YYMD6FD41MVNP3JS1GABZ8TRVX023PT.nft-trait.nft-trait](https://explorer.stacks.co/txid/0xd98b93eef09249c805fc47843cfdb817d23651106f093b8002d4e24e5a558b77?chain=testnet)

**SIP-010**
[ST1NXBK3K5YYMD6FD41MVNP3JS1GABZ8TRVX023PT.sip-010-trait-ft-standard.sip-010-trait](https://explorer.stacks.co/txid/0x99e01721e57adc2c24f7d371b9d302d581dba1d27250c7e25ea5f241af14c387?chain=mainnet)

**SIP-013**
[ST1NXBK3K5YYMD6FD41MVNP3JS1GABZ8TRVX023PT.sip013-semi-fungible-token-trait.sip013-semi-fungible-token-trait](https://explorer.stacks.co/txid/0x1f55f0f66777e79316b938941d6a6910fd2961e5e59a59d26266f788cdffb920?chain=testnet)

## References

 - [clarity-deployed-contracts](https://github.com/boomcrypto/clarity-deployed-contracts)

**Comment by whoabuddy** [comment]
+1, was looking for a testnet version of SIP-009/SIP-010 and saw that many projects deploy their own.

I could see it done two ways:

- a separate document outlining deployed contracts
- a specific section in the SIP for deployed contracts

I'm leaning toward the latter because then it would be each SIP author's job to provide/update the deployment information, and it keeps all the information for a particular SIP together in one place.

Maybe right after the **Activation** section add something for **Deployed Contracts** so it's more explicit? 

Also, should the trait name be listed in the link? Imagining two flows: one where the trait reference is copied directly from the SIP, and the other where the link is to the explorer/contract and you have to get the trait reference from the contract source. I prefer the latter, but it's definitely some extra steps.

For example, with SIP-010:

# Activation

This trait will be considered activated when this trait is deployed to mainnet, and 3 different implementations of the trait have been deployed to mainnet, no later than Bitcoin block 700000.

## Deployed Contracts

- mainnet: [SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard](https://explorer.stacks.co/txid/0x99e01721e57adc2c24f7d371b9d302d581dba1d27250c7e25ea5f241af14c387?chain=mainnet)
- testnet: [ST1NXBK3K5YYMD6FD41MVNP3JS1GABZ8TRVX023PT.sip-010-trait-ft-standard](https://explorer.stacks.co/txid/0x99e01721e57adc2c24f7d371b9d302d581dba1d27250c7e25ea5f241af14c387?chain=mainnet)
